feat(server): redzone
leia-uwu/resurviv pull request #26
Opened 2024-04-06 21:20 UTC by lmssiehdev

2024-04-07 21:37 UTC, leia-uwu requested changes

2024-04-07 21:37 UTC, leia-uwu commented on server/src/objects/gas.ts
> +    get data(): GasData {
why this getter? just set the packet gasData to the class instance

2024-04-07 21:37 UTC, leia-uwu commented on server/src/objects/gas.ts
> +        radNew: 534.6,
gas radius should be based on map size not hardcoded values

2024-04-07 21:37 UTC, leia-uwu commented on shared/utils/math.ts
> +    randomFloat(min: number, max: number): number {
we already have a random float function on util.ts
https://github.com/leia-uwu/resurviv/blob/master/shared/utils/util.ts#L36

2024-04-08 01:33 UTC, lmssiehdev commented on server/src/objects/gas.ts
> +        radOld: 0.7,
0.64 ( value in the wiki ) was showing the red zone even when it's inactive

2024-04-08 12:51 UTC, leia-uwu commented on shared/utils/math.ts
> +    distanceBetween(v1: Vec2, v2: Vec2): number {
theres `v2.distance`

2024-04-08 13:08 UTC, merged